services:
  - type: web
    name: university
    runtime: node
    buildCommand: cd ielts/Ielts-Mentor/Basic/bai-tap/ielts-writing-speaking/bai-viet-1 && yarn
    startCommand: cd ielts/Ielts-Mentor/Basic/bai-tap/ielts-writing-speaking/bai-viet-1 && yarn start